server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: cloud-getway
  cloud:
    gateway:
      routes:
       - id: route1
         uri: http://localhost:8080
         predicates:
         - Path=/user/get/**
