server:
  port: 8081

spring:
  application:
    name: cloud-provider

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.44.129:3306/db_ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123

mybatis:
  mapperLocations: classpath:mapper/*.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/



